### ISSUE TITLE
Improve performance of Scroll holaplex.com

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/holaplex#253]
The scrolling on holaplex.com is a bit sluggish. We might be able to improve it with  https://reactnative.dev/docs/virtualizedlist. 

The relevant code is in pages/index.tsx#600. Let's see if we can make it faster and smoother using the virtualizedList, or another method.

**Comment by austinmilt** [comment]
@dandlezzz can I get write access to upload a WIP branch, or would you rather I forked?

**Comment by austinmilt** [comment]
Just making some notes here... 

The main source of stutter looks to be the client caching of large images/videos that have to be re-rendered when scrolling. I'm sure there's a more accurate technical description of this, but the gist is the client is keeping a lot of data in-memory.

The virtualized list solution can help with this since those media are discarded by scrolling too far past them. In what I've tested so far, virtualizing definitely reduces scrolling stutter. However, in the most basic implementation, this introduces some additional issues because NFT metadata and media are reloaded every time a listing comes back into view:

1. added latency from downloading many 10s of MB, whether scrolling up or down
2. added network bandwidth usage, which is an issue on crappy internet 
3. previously seen listings show blank (`SkeletonListing`), which makes it slower to revisit a previously seen listing because you cant quickly identify them as you scroll

I think I can partially address 1-3 by caching the NFT metadata (without media) when it is first loaded. Still trying to figure out how to do that correctly. That way, the listing preview can still show the listing name, price, etc, and avoid the fetch to get the metadata which, for me, is ~100 ms each.

A more heavy-handed (long-term) solution would be to remotely cache a small(er)-sized static preview for each listing, by scaling static images and extracting+scaling a single frame from GIFs and videos. Then, the listing preview can show a static preview that could be (if necessary) animated/played on hover. It's obviously not as nice as getting the full quality, animated NFT right away. But, it would drastically reduce network bandwidth usage and load times.

**Comment by dandlezzz** [comment]
@austinmilt please fork.

**Comment by dandlezzz** [comment]
> Just making some notes here...
> 
> The main source of stutter looks to be the client caching of large images/videos that have to be re-rendered when scrolling. I'm sure there's a more accurate technical description of this, but the gist is the client is keeping a lot of data in-memory.
> 
> The virtualized list solution can help with this since those media are discarded by scrolling too far past them. In what I've tested so far, virtualizing definitely reduces scrolling stutter. However, in the most basic implementation, this introduces some additional issues because NFT metadata and media are reloaded every time a listing comes back into view:
> 
> 1. added latency from downloading many 10s of MB, whether scrolling up or down
> 2. added network bandwidth usage, which is an issue on crappy internet
> 3. previously seen listings show blank (`SkeletonListing`), which makes it slower to revisit a previously seen listing because you cant quickly identify them as you scroll
> 
> I can partially address 1-3 by caching the NFT metadata (without media) when it is first loaded. That way, the listing preview can still show the listing name, price, etc, and avoid the fetch to get the metadata which, for me, is ~100 ms each. However, this still replaces the media with the placeholder image, which is going to be the main thing by which users recognize the listing.
> 
> A more heavy-handed (long-term) solution would be to remotely cache a small(er)-sized static preview for each listing, by scaling static images and extracting+scaling a single frame from GIFs and videos. Then, the listing preview can show a static preview that could be (if necessary) animated/played on hover. It's obviously not as nice as getting the full quality, animated NFT right away. But, it would drastically reduce network bandwidth usage and load times. Given that Youtube does the same thing, it seems like an acceptable compromise.

Yes, this is all correct. Regarding image size, check out this recent PR, hasn't deployed yet. https://github.com/holaplex/holaplex/pull/245

**Comment by austinmilt** [comment]
@dandlezzz here's the WIP branch in my fork: https://github.com/holaplex/holaplex/compare/dev...austinmilt:%23253/improve-homepage-scroll?expand=1

**Comment by kespinola** [comment]
@austinmilt i think the second scroll bar is unavoidable when using a virtualized list. 

And we can't do pre-calculated heights or widths because image height is based on the width of the container.

Let me chat with the team but don't thing virtualization is going to be something we can use. Its unfortunate.

**Comment by kespinola** [comment]
I do like the metadata json caching though we are a few clicks from being able to swap the endpoint for discovery over to our graphql server which indexes the metadata json and returns a complete nft including image, descriptions, etc.

**Comment by austinmilt** [comment]
> I do like the metadata json caching though we are a few clicks from being able to swap the endpoint for discovery over to our graphql server which indexes the metadata json and returns a complete nft including image, descriptions, etc.

I think virtualization is largely unnecessary if this server contains cached scaled static images for each listing. The main source of stutter is from client-side caching of large images (usually GIFs) and autoplay videos. Otherwise, the cached metadata will reduce some lag from initially downloading the media, but the stutter will persist.

**Comment by austinmilt** [comment]
> @austinmilt i think the second scroll bar is unavoidable when using a virtualized list.

I am not a UX person, so forgive me if this is bad UX, but could the second scrollbar not be hidden and the primary scrollbar extended to simulate infinite scroll, while passing the scrolling status into the virtualized grid?

**Comment by austinmilt** [comment]
> And we can't do pre-calculated heights or widths because image height is based on the width of the container.

Yes, very true! I was thinking I could write a bit of responsive js to simulate the responsive features of CSS, and pass the dimensions into the virtualized grid, e.g. setting a min/max/desired width and auto-height for each preview, and calculating what the width should be based on the dimensions of the grid/view.

**Comment by austinmilt** [comment]
I've been doing a little more research tonight. 

Removing the second scrollbar can be accomplished with existing components (no in-house baked js) if I switch over to using the full `react-virtualized` library (see [WindowScroller](https://bvaughn.github.io/react-virtualized/#/components/WindowScroller))

**Comment by austinmilt** [comment]
I went to check back on holaplex.com and today, at least, the performance is way better. My page maxed out at 200 mb downloaded, which I believe is a good bit less than before. 

Has this ticket become obsolete?
